// Splash Screen
var view = UILabel()
view.frame = CGRect(x: 0, y: 0, width: 390, height: 828)
view.backgroundColor = .white

let layer0 = CALayer()
layer0.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1).cgColor
layer0.bounds = view.bounds
layer0.position = view.center
view.layer.addSublayer(layer0)

let layer1 = CALayer()
layer1.backgroundColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.2).cgColor
layer1.bounds = view.bounds
layer1.position = view.center
view.layer.addSublayer(layer1)

// Frame Login
var view = UILabel()
view.frame = CGRect(x: 0, y: 0, width: 390, height: 828)
view.backgroundColor = .white

let layer0 = CALayer()
layer0.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1).cgColor
layer0.bounds = view.bounds
layer0.position = view.center
view.layer.addSublayer(layer0)

let layer1 = CALayer()
layer1.backgroundColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.2).cgColor
layer1.bounds = view.bounds
layer1.position = view.center
view.layer.addSublayer(layer1)

// Info App Screen
var view = UILabel()
view.frame = CGRect(x: 0, y: 0, width: 390, height: 828)
view.backgroundColor = .white

let layer0 = CALayer()
layer0.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 1).cgColor
layer0.bounds = view.bounds
layer0.position = view.center
view.layer.addSublayer(layer0)

let layer1 = CALayer()
layer1.backgroundColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.2).cgColor
layer1.bounds = view.bounds
layer1.position = view.center
view.layer.addSublayer(layer1)
